### ISSUE TITLE
recent pandas sqlalchemy version dependency

### ISSUE THREAD

**Issue by brooks-eco** [DataShades/ckanext-charts#11]
pandas now only supports using SQLAlchemy>=2.0.0 according to https://pandas.pydata.org/docs/getting_started/install.html#sql-databases

Using AWS Marketplace: CKAN 2.11 pre-configured by Link Digital  as the base I got the error

```
2024-09-08 14:22:56,486 ERROR [ckan.config.middleware.flask_app] Query must be a string unless using sqlalchemy.
Traceback (most recent call last):

...snip...

   File "/usr/lib/ckan/default/lib/python3.12/site-packages/ckanext/charts/fetchers.py", line 69, in fetch_data
    df = pd.read_sql_query(
         ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ckan/default/lib/python3.12/site-packages/pandas/io/sql.py", line 526, in read_sql_query
    return pandas_sql.read_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ckan/default/lib/python3.12/site-packages/pandas/io/sql.py", line 2738, in read_query
    cursor = self.execute(sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ckan/default/lib/python3.12/site-packages/pandas/io/sql.py", line 2670, in execute
    raise TypeError("Query must be a string unless using sqlalchemy.")
TypeError: Query must be a string unless using sqlalchemy.
```
upgrading  SQLAlchemy  1.4.52 ->2.0.34  fixed the issue and ckanext-charts working on the CKAN 2.11 image

add to version dependencies in  https://github.com/DataShades/ckanext-charts/blob/master/setup.cfg?

**Comment by mutantsan** [comment]
Thanks, @brooks-eco. CKAN doesn't support SQLAlchemy 2+, so upgrading it is a bad idea.
I see, that `pandas` 2.1.4 is the [latest version](https://github.com/pandas-dev/pandas/blob/v2.1.4/requirements-dev.txt) that doesn't require SQLAlchemy 2+. I'll update the `setup.cfg` to limit max `pandas` version.
