### ISSUE TITLE
Internal Service Error 500 for multiple versions of CKAN

### ISSUE THREAD

**Issue by FrancisTembo** [DataShades/ckanext-charts#15]
I am encountering an internal server error (500) when attempting to install CKAN versions 2.10 and 2.11. This issue occurs on both Ubuntu 20.04 and 22.04 environments. Please advise on potential causes or solutions.

**Comment by mutantsan** [comment]
Hello, @FrancisTembo. Please, provide logs to understand the problem better.

**Comment by FrancisTembo** [comment]
@mutantsan Logs are clean; no errors in ckan-worker.stderr.log. I believe DataStore and xloader are configured because I can build tabular views from uploaded CSVs.

**Comment by mutantsan** [comment]
We don’t need worker logs here. We need logs from the daemon, that runs the `ckan run` cli command. For example, if you’re using supervisor, check its configs and see where you store your logs.

**Comment by FrancisTembo** [comment]
Aha thanks for the insight, I think this is the relevant information from `ckan-uwsgi.stderr.log`: 

`Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/config/middleware/../../views/resource.py", line 783, in get
    return base.render(u'package/new_view.html', extra_vars)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/lib/base.py", line 104, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/azureuser/ckanext-charts/ckanext/charts/templates/package/new_view.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates/package/new_view.html", line 1, in top-level template code
    {% extends "package/view_edit_base.html" %}
  File "/home/azureuser/ckanext-visualize/ckanext/visualize/templates/package/view_edit_base.html", line 12, in top-level template code
    {% set res = resource %}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/datastore/templates/package/resource_edit_base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/xloader/templates/package/resource_edit_base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates/package/resource_edit_base.html", line 4, in top-level template code
    {% set res = resource %}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates/package/base.html", line 4, in top-level template code
    {% set dataset_type = dataset_type or pkg.type or 'dataset' %}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/activity/templates/page.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/home/azureuser/ckanext-charts/ckanext/charts/templates/page.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates/page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/activity/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/home/azureuser/ckanext-excelforms/ckanext/excelforms/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/home/azureuser/ckanext-visualize/ckanext/visualize/templates/base.html", line 1, in top-level template code
    <!--
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates/base.html", line 107, in top-level template code
    {%- block page %}{% endblock -%}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates/page.html", line 19, in block 'page'
    {%- block content %}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates/page.html", line 22, in block 'content'
    {% block main_content %}
  File "/home/azureuser/ckanext-visualize/ckanext/visualize/templates/package/view_edit_base.html", line 38, in block 'main_content'
    {{ super() }}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates/page.html", line 74, in block 'main_content'
    {% block primary %}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates/page.html", line 87, in block 'primary'
    {% block primary_content %}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates/page.html", line 107, in block 'primary_content'
    {% block primary_content_inner %}
  File "/home/azureuser/ckanext-visualize/ckanext/visualize/templates/package/view_edit_base.html", line 27, in block 'primary_content_inner'
    {% block form %}{% endblock %}
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates/package/new_view.html", line 18, in block 'form'
    {% include 'package/snippets/view_form.html' %}
  File "/home/azureuser/ckanext-charts/ckanext/charts/templates/package/snippets/view_form.html", line 9, in top-level template code
    {% include form_template %}
  File "/home/azureuser/ckanext-charts/ckanext/charts/templates/charts/charts_form.html", line 1, in top-level template code
    {% snippet "charts/snippets/chart_create_form.html",
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
  File "charts/snippets/chart_create_form§resource_id,settings,form_builder,errors.html", line 1, in template
  File "/home/azureuser/ckanext-charts/ckanext/charts/templates/charts/snippets/chart_create_form.html", line 17, in top-level template code
    {% snippet "charts/snippets/charts_form_fields.html",
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
  File "charts/snippets/charts_form_fields§resource_id,data,builder,errors,exclude_tabs,user_chart_builder.html", line 1, in template
  File "/home/azureuser/ckanext-charts/ckanext/charts/templates/charts/snippets/charts_form_fields.html", line 11, in top-level template code
    {% set tab_fields = builder.get_fields_by_tab(tab) %}
  File "/home/azureuser/ckanext-charts/ckanext/charts/chart_builders/base.py", line 253, in get_fields_by_tab
    fields = self.get_expanded_form_fields()
  File "/home/azureuser/ckanext-charts/ckanext/charts/chart_builders/base.py", line 211, in get_expanded_form_fields
    return self.expand_schema_fields(
  File "/home/azureuser/ckanext-charts/ckanext/charts/chart_builders/base.py", line 224, in expand_schema_fields
    expanded_schemas = _expand_schemas({"schema": {"fields": fields}})
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/scheming/plugins.py", line 667, in _expand_schemas
    schema[grouping] = [
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/scheming/plugins.py", line 668, in <listcomp>
    _expand(schema, field)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/scheming/plugins.py", line 649, in _expand
    if preset not in _SchemingMixin._presets:
TypeError: argument of type 'NoneType' is not iterable
`

**Comment by FrancisTembo** [comment]
I fixed this by just activating the `ckanext-scheming` plugin.
